# Generated by Django 3.0.2 on 2020-01-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to=None, verbose_name='dish picture')),
                ('name', models.CharField(max_length=50, verbose_name='dish name')),
                ('calorie', models.IntegerField(verbose_name='dish calorie')),
                ('like', models.IntegerField(verbose_name='dish like amount')),
                ('dislike', models.IntegerField(verbose_name='dish dislike amount')),
                ('tag', models.ManyToManyField(to='dish.Tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
