# Generated by Django 3.0.2 on 2020-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='carbohydrate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='energy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='energy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='fat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='protein'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='sodium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='sodium'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='water',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='water'),
            preserve_default=False,
        ),
    ]
