# Generated by Django 3.0.2 on 2020-01-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_auto_20200130_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dislike',
            field=models.IntegerField(default=1, verbose_name='dish dislike amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='like',
            field=models.IntegerField(default=1, verbose_name='dish like amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='carbohydrate'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='energy',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='energy'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='fat'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='protein'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='sodium',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='sodium'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='water',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='water'),
        ),
    ]
