# Generated by Django 3.0.2 on 2020-01-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0004_auto_20200130_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(upload_to=None, verbose_name='dish picture'),
        ),
    ]
