# Generated by Django 3.1 on 2020-08-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0006_auto_20200810_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='water',
        ),
    ]
