# Generated by Django 3.1 on 2020-08-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0010_auto_20200818_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(upload_to='media', verbose_name='dish picture'),
        ),
    ]
