# Generated by Django 3.1 on 2020-08-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0011_auto_20200818_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='dish picture'),
        ),
    ]
