# Generated by Django 3.1 on 2020-10-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0012_auto_20200818_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='per_calorie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='calorie per 100g'),
            preserve_default=False,
        ),
    ]
