# Generated by Django 3.1 on 2020-11-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0013_dish_per_calorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Dish orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Dish views'),
            preserve_default=False,
        ),
    ]
