# Generated by Django 3.0.2 on 2020-01-27 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.NullBooleanField(verbose_name='like')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.Dish', verbose_name='dish')),
            ],
            options={
                'verbose_name': 'LikeDish',
                'verbose_name_plural': 'LikeDishs',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=50, verbose_name='user open_id')),
                ('name', models.CharField(max_length=50, verbose_name='user name')),
                ('avatar', models.FileField(upload_to=None, verbose_name='user avatar')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='user weight')),
                ('min_calorie', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='user min_calorie')),
                ('max_calorie', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='user max_calorie')),
                ('like_dish', models.ManyToManyField(through='user.LikeDish', to='dish.Dish', verbose_name='like_dish')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='likedish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='user'),
        ),
    ]
