# Generated by Django 3.0.2 on 2020-02-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchitem', '0003_auto_20200217_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchitem',
            name='count',
            field=models.IntegerField(default=0, verbose_name='search count'),
        ),
    ]
