# Generated by Django 3.0.2 on 2020-01-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200129_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_calorie',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='user max_calorie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='min_calorie',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='user min_calorie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='user weight'),
        ),
    ]
