# Generated by Django 3.0.2 on 2020-01-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200131_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='defualt name', max_length=50, verbose_name='user name'),
            preserve_default=False,
        ),
    ]
