# Generated by Django 3.0.2 on 2020-02-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='open_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='max_calorie',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=8, verbose_name='user max_calorie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='min_calorie',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8, verbose_name='user min_calorie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=7, verbose_name='user weight'),
        ),
    ]
