# Generated by Django 3.0.2 on 2020-02-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200203_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.BooleanField(default=False, verbose_name='if diet'),
        ),
        migrations.AddField(
            model_name='user',
            name='target_weight',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=7, verbose_name='user target weight'),
        ),
    ]
