# Generated by Django 3.0.2 on 2020-02-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='target_weight',
            field=models.IntegerField(default=60, verbose_name='user target weight'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default=60, verbose_name='user weight'),
        ),
    ]
