# Generated by Django 3.0.5 on 2020-04-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200215_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='weight change rate'),
        ),
    ]
