# Generated by Django 4.0.1 on 2022-01-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='male', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(default=170),
        ),
        migrations.AlterField(
            model_name='likedish',
            name='like',
            field=models.BooleanField(null=True, verbose_name='like'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
