# Generated by Django 3.1 on 2020-08-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calorie', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('dietary_fiber', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vitaminC', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('calcium', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sodium', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.IntegerField()),
                ('expiration', models.DateTimeField()),
            ],
        ),
    ]
