# Generated by Django 3.1 on 2020-08-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0002_auto_20200810_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration',
            field=models.DateTimeField(),
        ),
    ]
