# Generated by Django 3.1 on 2020-08-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0003_auto_20200810_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token',
            field=models.CharField(default=123123, max_length=32),
            preserve_default=False,
        ),
    ]
