# Generated by Django 3.0.2 on 2020-01-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishorder',
            old_name='dish_id',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='dishorder',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='user_id',
            new_name='user',
        ),
    ]
