# Generated by Django 3.0.2 on 2020-01-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200128_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='order date'),
        ),
    ]
